### ISSUE TITLE
Compilation Fails with createMCInstPrinter Error

### ISSUE THREAD

**Issue by seanmkauffman** [avr-llvm/clang#3]
```
llvm[4]: Compiling ParseStmtAsm.cpp for Debug+Asserts build
/home/seanmk/workspace/llvm/tools/clang/lib/Parse/ParseStmtAsm.cpp:533:38: error: 
      reference to type 'const llvm::Triple' could not bind to an rvalue of type
      'int'
      TheTarget->createMCInstPrinter(1, *MAI, *MII, *MRI, *STI));
                                     ^
/home/seanmk/workspace/llvm/include/llvm/Support/TargetRegistry.h:411:54: note: 
      passing argument to parameter 'T' here
    MCInstPrinter *createMCInstPrinter(const Triple &T, unsigned SyntaxVariant,
                                                     ^
1 error generated.
```

**Comment by dylanmckay** [comment]
I have `llvm` and `clang` at `master` (llvm: 7e8c7af2, clang: 00a0b3863a), and compilation is successful - I am not getting this error.

**Comment by dylanmckay** [comment]
Note that `Target::createMCInstPrinter` is declared at `TargetRegistry.h:414` (see the file [here](https://github.com/avr-llvm/llvm/blob/avr-support/include/llvm/Support/TargetRegistry.h#L414)).

It seems like you have the incorrect version of TargetRegistry. One which has a different signature and defined on a different line.
