### ISSUE TITLE
Make double 32-bits

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/clang#7]
This is a quirk of AVR - see the AVR ABI description [here](https://gcc.gnu.org/wiki/avr-gcc#Type_Layout).

This causes any code compiled which uses `double` values to fail linking.

**Comment by Sh4rK** [comment]
Isn't this fixed in 26488ca543c8d1bed22a8e3aefcb6a2f218b9edc?

**Comment by dylanmckay** [comment]
I believe so :)
